### ISSUE TITLE
1 group?

### ISSUE THREAD

**Issue by OnlyBelter** [stephaniehicks/qsmooth#12]
I just read your wonderful paper and would like to ask a question.

What's the meaning of the results if I assign 1 single group for all samples? Is `qsmooth` equivalent to standard quantile nomalization under this situation?

The problem I want to solve is that **simulated bulk RNA-seq data by single cell data** (dataset1) separated far away from **real bulk RNA-seq data** (dataset2, such as data from TCGA) if we check the first two principal components. Similar to the third column of `Fig. 5.`, dataset1 and dataset2 are two separated groups in PC1/PC2 figure. We want to eliminate the difference between two groups. Can we say this difference is caused by batch effect and can be removed by quantile normalization?

Thanks!

**Comment by stephaniehicks** [comment]
Hi @OnlyBelter, yes in the case that there is only 1 group, I believe it is the same as standard quantile normalization.

**Comment by perinom** [comment]
Just to follow up on the question, currently if there's only 1 group a standard `qsmooth()` call fails with
```
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```
Is there a way to run standard quantile normalization from within `qsmooth`  in these cases or should I use external resources?

**Comment by stephaniehicks** [comment]
Hi, 

If there is only one group, you are essentially doing quantile normalization. `qsmooth` was designed for at minimum two or more groups. Thanks!
