### ISSUE TITLE
Question about combining qsmooth and spatial quantile normalization

### ISSUE THREAD

**Issue by cadyyuheng** [stephaniehicks/qsmooth#13]
Dear qsmooth team,

Thank you so much for sharing this package. I am working on a large multi-batch RNA-seq dataset and aiming to conduct co-expression analysis to identify consensus gene modules. Both the qsmooth and spqn packages have caught my attention, and I want to try both. For my multi-batch data, I hope to first remove the batch effect and then try out spatial quantile normalization before proceeding downstream to WGCNA. However, I wonder if I will over-correct my data if I use the log + 1 results from qsmooth as input for spqn to obtain a corrected correlation matrix. I would greatly appreciate any insights you can provide regarding this proposed workflow.

Thank you in advance for your help!

**Comment by stephaniehicks** [comment]
Hi @cadyyuheng! thanks for your interest in the package. My recommendation would be to remove the top PCs like in the `spqn` package. I haven't tried this with `qsmooth`, but I'd be curious to see how this works for you!

**Comment by cadyyuheng** [comment]
Thanks for your reply @stephaniehicks! We ended up only using `qsmooth` without using `spqn` package. It worked well for us!

**Comment by stephaniehicks** [comment]
Awesome, glad to hear it was helpful!
