### ISSUE TITLE
Typo in the example of function `qsmooth`

### ISSUE THREAD

**Issue by SONGDONGYUAN1994** [stephaniehicks/qsmooth#3]
At the last line of the example: `qsNorm <- qsmooth(object = exprs(bodymapRat), groupFactor = pd$pd$group)`. Seem to have double `$` here.

**Comment by stephaniehicks** [comment]
Thanks @SONGDONGYUAN1994 for your issue! I fixed the typo in the example in the latest commit (https://github.com/stephaniehicks/qsmooth/commit/8daf30ff31c23248d88c3d2c5228a7fa9f7c1a82). Also, I'm preparing to submit to Bioconductor this week. Will close issue now that the typo is fixed.
