### ISSUE TITLE
Submit qsmooth to CRAN or Bioconductor

### ISSUE THREAD

**Issue by jma1991** [stephaniehicks/qsmooth#4]
I am currently using qsmooth in my package for analysis of DamID-seq data (https://github.com/jma1991/Daim) and would like to submit the package to Bioconductor. However, I cannot submit a package which "depends on any package (or version of a package) that is not (yet) available on CRAN or Bioconductor". Is there any plan to submit qsmooth to either of these repositories?

**Comment by stephaniehicks** [comment]
Hi! Thanks for your message and for using qsmooth! It’s been on my to-do list for a while now, but this is a great nudge. I will submit the package to Bioconductor this week and keep you posted on the progress on this thread. Thanks again!

**Comment by stephaniehicks** [comment]
Quick update @jma1991: I'm currently fighting with passing `R CMD BiocCheck` :( but this should be sorted out in the next day or two. As soon as I get past that, I will be submitting `qsmooth` and `bodymapRat` to Bioc.

**Comment by jma1991** [comment]
@stephaniehicks No problem, thank you for the update!

**Comment by stephaniehicks** [comment]
another update @jma1991: qsmooth passes `R CMD BiocCheck` !  I pushed changes here (https://github.com/stephaniehicks/qsmooth/commit/8daf30ff31c23248d88c3d2c5228a7fa9f7c1a82). I've got some meetings this morning, but should definitely be able to submit to Bioconductor this afternoon or tomorrow at the latest.

**Comment by stephaniehicks** [comment]
another update @jma1991: I'm so sorry about my super slow response. I've submitted an experimental data package `bodymapRat` (https://github.com/Bioconductor/Contributions/issues/1026) to Bioconductor. This is a package that is used in all the examples for the `qsmooth` package. As soon as it get through the moderation round (should be easy because it's just a data package), I will submit `qsmooth`. Thanks for your patience

**Comment by jma1991** [comment]
Absolutely no worries @stephaniehicks - thank you for the update!

**Comment by stephaniehicks** [comment]
@jma1991: `qsmooth` has been submitted and builds with no errors or warnings. https://github.com/Bioconductor/Contributions/issues/1026#issuecomment-467173968

Not sure how long the next phase will take, but will keep you posted.

**Comment by stephaniehicks** [comment]
@jma1991 `qsmooth` has been accepted into Bioconductor devel: https://www.bioconductor.org/packages/qsmooth.

I will close this issue now. Thanks!

**Comment by jma1991** [comment]
This is great news, thank you very much!
