### ISSUE TITLE
install error: ERROR: this R is version 3.5.1, package 'qsmooth' requires R >= 3.6.0

### ISSUE THREAD

**Issue by Wenhao-Jin** [stephaniehicks/qsmooth#5]
Hello,
I'm trying to install qsmooth, but got an error listed below. Since the newest R version nowadays is still 3.5.*, it seems weird to get this error. Would you have any suggestions on this? Great thanks!

The downloaded source packages are in
	'/tmp/RtmpGA7egn/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
   checking for file '/tmp/RtmpGA7egn/remotes6fd128c80a12/stephaniehicks-qsmoothv  checking for file '/tmp/RtmpGA7egn/remotes6fd128c80a12/stephaniehicks-qsmooth-a38c077/DESCRIPTION' (545ms)
-  preparing 'qsmooth':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'qsmooth_0.99.1.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'
   
ERROR: this R is version 3.5.1, package 'qsmooth' requires R >= 3.6.0
Error in i.p(...) : 
  (converted from warning) installation of package '/tmp/RtmpGA7egn/file6fd14341f760/qsmooth_0.99.1.tar.gz' had non-zero exit status
> install_github("stephaniehicks/qsmooth")
Downloading GitHub repo stephaniehicks/qsmooth@master
Skipping 14 packages ahead of CRAN: annotate, AnnotationDbi, Biobase, BiocGenerics, BiocParallel, genefilter, GenomeInfoDb, GenomeInfoDbData, GenomicRanges, IRanges, limma, S4Vectors, XVector, zlibbioc
   checking for file '/tmp/RtmpGA7egn/remotes6fd1a7687f4/stephaniehicks-qsmooth-v  checking for file '/tmp/RtmpGA7egn/remotes6fd1a7687f4/stephaniehicks-qsmooth-a38c077/DESCRIPTION' (597ms)
-  preparing 'qsmooth':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'qsmooth_0.99.1.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'
   
ERROR: this R is version 3.5.1, package 'qsmooth' requires R >= 3.6.0
Error in i.p(...) : 
  (converted from warning) installation of package '/tmp/RtmpGA7egn/file6fd113250397/qsmooth_0.99.1.tar.gz' had non-zero exit status

**Comment by stephaniehicks** [comment]
Hi @Wenhao-Jin! Thanks for your message. I changed to the R-devel because I'm in the process of submitting the package to Bioconductor (https://github.com/Bioconductor/Contributions/issues/1026), which requires that R-devel be used for this part of the cycle. Once it's accepted into Bioconductor, you will be able to download it directly from there. For now though, I will close this issue.
