### ISSUE TITLE
Installation for R version < 3.6?

### ISSUE THREAD

**Issue by rosalinamae** [stephaniehicks/qsmooth#6]
Hi there,

I would like to get started using qsmooth, but it seems the newest version requires R >= 3.6. Is it possible to install an older version that is compatible with R 3.5?

Thank you so much.

**Comment by stephaniehicks** [comment]
Hi @rosalinamae! I apologize in my delayed response. Hmm, is there a reason you need R 3.5?

**Comment by stephaniehicks** [comment]
Closing this issue for now.
