### ISSUE TITLE
Questions on the advantages of qsmooth

### ISSUE THREAD

**Issue by chilampoon** [stephaniehicks/qsmooth#7]
Hello, 

I have been confused about the differences between doing qsmooth for the whole dataset and doing quantile normalization in each tissue (tissue-aware QN) since I read the YARN and qsmooth paper. The qsmooth paper stated that the advantages of qsmooth include:

1. preservation of global differences in distributions corresponding to different biological conditions
2. non-reliance on external information

I think these are related to the weights assigned to each quantile, so the tissue-aware QN cannot keep global differences? Then how to explain this difference? And is qsmooth really better than tissue-aware QN? Thanks.

**Comment by stephaniehicks** [comment]
Hi @chilampoon, 

Thanks for your interest! Yes, you are correct. The weights assigned to each quantile in qsmooth are related to the amount of variability within and between biological groups. 

Regarding tissue-aware QN -- I am not an author on the YARN paper (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1847-x) and would suggest reaching out to the first author to find out more details. 

Hope this helps! 

All the best, 
Stephanie

**Comment by stephaniehicks** [comment]
Closing this issue.
