### ISSUE TITLE
Using qsmooth in the generic Affymetrix processing pipeline

### ISSUE THREAD

**Issue by axitamm** [stephaniehicks/qsmooth#8]
Thank you for this amazing package (and quantro)!

I would like to obtain your best thoughts about integrating qsmooth into the generic Affymetrix rma processing pipeline. By generic, I mean the following:

library(affy)

#read the .cel files in the working directory
expdata<-ReadAffy() 

#the generic "rma" processing (which as you know can also be achieved by using the function affy::rma instead of affy::expresso)
eset <- expresso(expdata, bgcorrect.method="rma", **normalize.method="quantiles"**, pmcorrect.method="pmonly", summary.method="medianpolish") 

How do you suggest smooth quantile normalization be incorporated **in the code above**?

Thank you!

**Comment by stephaniehicks** [comment]
Hi @axitamm, 

Could you post your comment on the Bioconductor Support site (https://support.bioconductor.org)? I will answer any problems about the package itself here, but prefer to answer the types of questions you are asking on the support site. 

Thanks
Stephanie

**Comment by stephaniehicks** [comment]
Closing this issue too.
